@gender="male"

GET https://localhost:7097/User/by-gender{{gender}}
x-api-key = E12D9B91D9F74DBDA6D25A3EF3104102

###

GET https://localhost:7097/User/popular-country
x-api-key = E12D9B91D9F74DBDA6D25A3EF3104102